import { useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Project = { name: string; description: string; stack: string; status: string; visibility: string; link?: string; featured?: boolean }

const projects: Project[] = [
  { name: 'InvestTrack', description: 'Private Java project in active development for tracking investments with a cleaner view of financial decisions.', stack: 'Java', status: 'ACTIVE', visibility: 'PRIVATE', link: 'https://github.com/ubvc04/InvestTrack', featured: true },
  { name: 'Self-healing-infrastructure', description: 'An exploration of resilient infrastructure patterns and automated recovery workflows.', stack: 'Go', status: 'RESEARCH', visibility: 'PUBLIC', link: 'https://github.com/ubvc04/self-healing-infrastructure' },
  { name: 'Intrusion-Detection-System', description: 'Hybrid HIDS and NIDS concept for monitoring system events and network traffic in real time.', stack: 'Python / Security', status: 'LAB', visibility: 'PRIVATE', link: 'https://github.com/ubvc04/Intrusion-Detection-System' },
  { name: 'Smart-Attendance-System', description: 'Face-recognition attendance workflow with an admin panel and local data storage.', stack: 'HTML / Flask / SQLite', status: 'SHIPPED', visibility: 'PUBLIC', link: 'https://github.com/ubvc04/Smart-Attendance-System' },
  { name: 'SignLang-AI', description: 'Real-time sign language to text translator using webcam input and a CNN classifier.', stack: 'Python / OpenCV', status: 'SHIPPED', visibility: 'PUBLIC', link: 'https://github.com/ubvc04/SignLang-AI' },
  { name: 'Custom-HTTP-Server', description: 'A low-level private project for understanding HTTP fundamentals through implementation.', stack: 'C', status: 'BUILDING', visibility: 'PRIVATE' },
]

const skills = [['Java / Spring Boot', 'BACKEND'], ['Angular / TypeScript', 'FRONTEND'], ['REST APIs / JWT', 'PLATFORM'], ['MySQL / SQL', 'DATA'], ['Linux / Bash', 'SYSTEMS'], ['Security tooling', 'LAB']]
const commandOutput: Record<string, string[]> = {
  about: ['Bavesh Chowdary', 'Full-stack developer + cybersecurity learner', 'Building software with curiosity and care.'],
  skills: ['Java', 'Spring Boot', 'Angular', 'TypeScript', 'MySQL', 'Linux', 'Shell scripting', 'Cybersecurity'],
  projects: projects.map((project) => `${project.name}  ::  ${project.status}`),
  security: ['Linux CLI        [████████░░]', 'Shell scripting  [███████░░░]', 'Networking       [██████░░░░]', 'Web security     [██████░░░░]', 'Automation       [███████░░░]'],
  opensource: ['Open to learning from and contributing to meaningful tools.', 'Focus: Java, web platforms, security automation.'],
  github: ['github.com/ubvc04', 'Public repositories are linked throughout this page.', 'No activity is fabricated here.'],
  contact: ['Email: baveshchowdary1@gmail.com', 'GitHub: github.com/ubvc04'],
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [terminalInput, setTerminalInput] = useState('')
  const [terminalLines, setTerminalLines] = useState<string[]>(['visitor@bavesh:~$ help', 'Try: about, skills, projects, security, github, contact, clear'])
  const runCommand = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const command = terminalInput.trim().toLowerCase(); if (!command) return; if (command === 'clear') setTerminalLines([]); else setTerminalLines((lines) => [...lines, `visitor@bavesh:~$ ${command}`, ...(commandOutput[command] ?? [`command not found: ${command}`, 'Type help for available commands.'])]); setTerminalInput('') }

  return (
    <div className="app-shell">
      <header className="topbar"><a className="brand" href="#home"><span className="brand-mark">&gt;_</span> BAVES<span className="muted">.dev</span></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? '×' : '☰'}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{['about', 'stack', 'projects', 'security', 'opensource'].map((item) => <a key={item} href={`#${item}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<a href="mailto:baveshchowdary1@gmail.com">connect</a></nav><div className="system-status"><span /> SYSTEM ONLINE</div></header>
      <main>
        <section className="hero section-wrap" id="home"><div className="hero-copy"><div className="eyebrow">PROJECT SHOWCASE / SOFTWARE + SECURITY</div><h1>Bavesh<br /><em>Chowdary</em></h1><p className="hero-lede">A working showcase of applications, experiments and systems I have built with Java, web technologies and security-minded thinking.</p><div className="hero-actions"><a className="button primary" href="#projects">Explore projects <span>↗</span></a><a className="button ghost" href="mailto:baveshchowdary1@gmail.com">Send an email <span>→</span></a></div><div className="hero-meta"><span><b>01</b> Applications</span><span><b>02</b> Systems</span><span><b>03</b> Security labs</span></div></div><div className="hero-terminal terminal-card"><div className="terminal-top"><span className="dots">● ● ●</span><span>~/home/portfolio</span><span>v1.0.26</span></div><div className="terminal-body"><p><span className="green">┌──[</span> visitor@bavesh <span className="green">]──[</span> ~/home <span className="green">]</span></p><p className="blank">│</p><p><span className="green">│ $</span> ls ./showcase</p><p><span className="green">│ &gt;</span> full-stack-apps/</p><p><span className="green">│ &gt;</span> security-labs/</p><p><span className="green">│ &gt;</span> experiments/</p><p className="blank">│</p><p><span className="green">│ $</span> status</p><p><span className="green">│ &gt;</span> Building. Learning. Securing.</p><p><span className="green">└───────────────</span><span className="cursor">_</span></p></div></div><div className="scroll-note">SCROLL TO EXPLORE <span>↓</span></div></section>
        <section className="ticker"><div>BUILD <span>↓</span> SECURE <span>↓</span> LEARN <span>↓</span> AUTOMATE <span>↓</span> CONTRIBUTE</div></section>
        <section className="section-wrap split-section" id="about"><div className="section-label">01 / ABOUT</div><div className="section-content"><p className="section-kicker">$ cat about_me.txt</p><h2>Curious about the layers<br /><span>beneath the interface.</span></h2><p className="body-copy">I am a full-stack developer focused on Java, Spring Boot and Angular. Alongside building applications, I explore Linux, shell scripting and cybersecurity through hands-on projects and command-line experimentation.</p><div className="info-grid"><div><span>ROLE</span><strong>Full Stack Developer</strong></div><div><span>BACKEND</span><strong>Java / Spring Boot</strong></div><div><span>FRONTEND</span><strong>Angular / TypeScript</strong></div><div><span>DATABASE</span><strong>MySQL / SQL</strong></div></div></div></section>
        <section className="section-wrap stack-section" id="stack"><div className="section-label">02 / TOOLKIT</div><div className="section-content"><p className="section-kicker">$ ls -la /skills</p><h2>The tools I use to<br /><span>make things real.</span></h2><div className="skill-grid">{skills.map(([name, type], index) => <div className="skill-row" key={name}><span className="skill-number">0{index + 1}</span><strong>{name}</strong><span className="skill-type">{type}</span></div>)}</div></div></section>
        <section className="section-wrap projects-section" id="projects"><div className="section-label">03 / PROJECT SHOWCASE</div><div className="section-content"><div className="heading-row"><div><p className="section-kicker">$ find ./showcase -type f</p><h2>Things I have built,<br /><span>tested and shipped.</span></h2></div><a className="text-link" href="https://github.com/ubvc04" target="_blank" rel="noreferrer">View GitHub ↗</a></div><div className="project-grid">{projects.map((project, index) => <article className={project.featured ? 'project-card featured' : 'project-card'} key={project.name}><div className="project-top"><span>PROJECT_{String(index + 1).padStart(2, '0')}</span><span className={`status ${project.status.toLowerCase()}`}>● {project.status}</span></div><h3>{project.name}</h3><p>{project.description}</p><div className="project-bottom"><span>{project.stack}</span><span>{project.visibility}</span></div>{project.link && <a className="project-link" href={project.link} target="_blank" rel="noreferrer">Open repository ↗</a>}</article>)}</div></div></section>
        <section className="section-wrap security-section" id="security"><div className="section-label">04 / SECURITY LAB</div><div className="section-content"><p className="section-kicker">$ ./security_profile.sh</p><div className="security-layout"><div><h2>Learn the system.<br /><span>Question the defaults.</span></h2><p className="body-copy">Cybersecurity is an active learning track for me: Linux CLI, networking, web security fundamentals, security automation and CTF-style problem solving. These are visual notes from the lab, not certifications or formal proficiency claims.</p><div className="lab-tags">{['Linux CLI', 'Bash scripting', 'Networking', 'Web application security', 'Log analysis', 'BlackArch Linux'].map((tag) => <span key={tag}>+ {tag}</span>)}</div></div><div className="meter-panel">{[['Linux CLI', 80], ['Shell scripting', 70], ['Networking', 60], ['Web security', 60], ['Automation', 70]].map(([label, width]) => <div className="meter" key={label as string}><div><span>{label}</span><span>{width}% / exploring</span></div><i><b style={{ width: `${width}%` }} /></i></div>)}</div></div></div></section>
        <section className="section-wrap current-section" id="opensource"><div className="section-label">05 / CURRENTLY WORKING ON</div><div className="section-content"><p className="section-kicker">$ ps aux | grep projects</p><div className="current-card"><div className="current-icon">IT</div><div><div className="current-title"><h3>InvestTrack</h3><span className="status active">● ACTIVE</span></div><p>Building a private Java application for tracking investments and making portfolio decisions easier to inspect.</p><div className="current-tags"><span>Java</span><span>Private repository</span><span>Updated recently</span></div></div><a href="https://github.com/ubvc04/InvestTrack" target="_blank" rel="noreferrer" className="arrow-button">↗</a></div><div className="opensource-note"><span className="quote-mark">“</span><div><h3>Open source is a practice, not a badge.</h3><p>I am interested in contributing to useful projects, improving existing tools, learning from experienced developers, and collaborating on meaningful software.</p><a className="text-link" href="https://github.com/ubvc04" target="_blank" rel="noreferrer">Find me on GitHub ↗</a></div></div></div></section>
        <section className="terminal-playground section-wrap"><div className="section-label">06 / PLAYGROUND</div><div className="section-content"><p className="section-kicker">$ ssh visitor@bavesh</p><div className="playground terminal-card"><div className="terminal-top"><span className="dots">● ● ●</span><span>visitor@bavesh:~</span><span>interactive</span></div><div className="playground-output">{terminalLines.map((line, index) => <div key={`${line}-${index}`} className={line.startsWith('visitor@') ? 'prompt-line' : ''}>{line}</div>)}</div><form onSubmit={runCommand} className="command-line"><span>visitor@bavesh:~$</span><input value={terminalInput} onChange={(event) => setTerminalInput(event.target.value)} aria-label="Terminal command" autoComplete="off" /><button aria-label="Run command">↵</button></form></div></div></section>
      </main><footer className="footer"><span>$ echo "Keep building. Keep learning."</span><a href="mailto:baveshchowdary1@gmail.com">Send me an email ↗</a><span className="footer-status">SYSTEM STATUS: ONLINE ●</span></footer>
    </div>
  )
}

export default App
